In [44]:
import numpy as np
import scipy as sp
import sympy as sym
import time 

In [45]:
data = [
    (np.array((19, 13, 30)), np.array((-2,  1, -2))),
    (np.array((18, 19, 22)), np.array((-1, -1, -2))),
    (np.array((20, 25, 34)), np.array((-2, -2, -4))),
    (np.array((12, 31, 28)), np.array((-1, -2, -1))),
    (np.array((20, 19, 15)), np.array(( 1, -5, -3)))
]

$$
p + v*t_i = p_i + v_i * t_i
$$

In [56]:
px, py, pz = sym.symbols('px py pz')
vx, vy, vz = sym.symbols('vx vy vz')
t0, t1, t2 = sym.symbols('t0 t1 t2')
P0x, P0y, P0z = sym.symbols('P0x P0y P0z')
P1x, P1y, P1z = sym.symbols('P1x P1y P1z')
P2x, P2y, P2z = sym.symbols('P2x P2y P2z')
V0x, V0y, V0z = sym.symbols('V0x V0y V0z')
V1x, V1y, V1z = sym.symbols('V1x V1y V1z')
V2x, V2y, V2z = sym.symbols('V2x V2y V2z')

p = sym.Matrix([px, py, pz])
v = sym.Matrix([vx, vy, vz])

P0 = sym.Matrix([P0x, P0y, P0z])
P1 = sym.Matrix([P1x, P1y, P1z])
P2 = sym.Matrix([P2x, P2y, P2z])

V0 = sym.Matrix([V0x, V0y, V0z])
V1 = sym.Matrix([V1x, V1y, V1z])
V2 = sym.Matrix([V2x, V2y, V2z])


t0x_sol = sym.solve(((p + v * t0) - (P0 + V0 * t0))[0], [t0])[0]
t0y_sol = sym.solve(((p + v * t0) - (P0 + V0 * t0))[1], [t0])[0]
t0z_sol = sym.solve(((p + v * t0) - (P0 + V0 * t0))[2], [t0])[0]
t1x_sol = sym.solve(((p + v * t1) - (P1 + V1 * t1))[0], [t1])[0]
t1y_sol = sym.solve(((p + v * t1) - (P1 + V1 * t1))[1], [t1])[0]
t1z_sol = sym.solve(((p + v * t1) - (P1 + V1 * t1))[2], [t1])[0]
t2x_sol = sym.solve(((p + v * t2) - (P2 + V2 * t2))[0], [t2])[0]
t2y_sol = sym.solve(((p + v * t2) - (P2 + V2 * t2))[1], [t2])[0]
t2z_sol = sym.solve(((p + v * t2) - (P2 + V2 * t2))[2], [t2])[0]

print("  t0 =", t0x_sol, '=', t0y_sol, '=', t0z_sol)
print("  t1 =", t1x_sol, '=', t1y_sol, '=', t1z_sol)
print("  t2 =", t2x_sol, '=', t2y_sol, '=', t2z_sol)

t0xy = t0x_sol - t0y_sol

print("from t0x and t0y:")
print("  ", (t0x_sol - t0y_sol).__mul__(V0x - vx).__mul__(V0y - vy).expand().simplify(), "= 0")
print("from t0x and t0z:")
print("  ", (t0x_sol - t0z_sol).__mul__(V0x - vx).__mul__(V0z - vz).expand().simplify(), "= 0")
print("We can rewrite the equations above as:")
print("  ", (t0x_sol - t0y_sol)
    .__mul__(V0x - vx)
    .__mul__(V0y - vy)
    .expand()
    .simplify()
    .__add__(px*vy - py*vx)
    , "=", px*vy - py*vx)
print("  ", (t0x_sol - t0z_sol)
    .__mul__(V0x - vx)
    .__mul__(V0z - vz)
    .expand().simplify()
    .__add__(px*vz - pz*vx)
    , "=", px*vz - pz*vx)
print("we see that RHS is independent of the exact hailstone we are looking at")
equations = [
    (t0x_sol - t0y_sol)
    .__mul__(V0x - vx)
    .__mul__(V0y - vy)
    .expand()
    .simplify()
    .__add__(px*vy - py*vx) - (t1x_sol - t1y_sol)
    .__mul__(V1x - vx)
    .__mul__(V1y - vy)
    .expand()
    .simplify()
    .__add__(px*vy - py*vx).simplify(),
    (t0x_sol - t0z_sol)
    .__mul__(V0x - vx)
    .__mul__(V0z - vz)
    .expand()
    .simplify()
    .__add__(px*vz - pz*vx) - (t1x_sol - t1z_sol)
    .__mul__(V1x - vx)
    .__mul__(V1z - vz)
    .expand()
    .simplify()
    .__add__(px*vz - pz*vx).simplify(),
    (t0y_sol - t0z_sol)
    .__mul__(V0y - vy)
    .__mul__(V0z - vz)
    .expand()
    .simplify()
    .__add__(py*vz - pz*vy) - (t1y_sol - t1z_sol)
    .__mul__(V1y - vy)
    .__mul__(V1z - vz)
    .expand()
    .simplify()
    .__add__(py*vz - pz*vy).simplify(),
    (t0x_sol - t0y_sol)
    .__mul__(V0x - vx)
    .__mul__(V0y - vy)
    .expand()
    .simplify()
    .__add__(px*vy - py*vx) - (t2x_sol - t2y_sol)
    .__mul__(V2x - vx)
    .__mul__(V2y - vy)
    .expand()
    .simplify()
    .__add__(px*vy - py*vx).simplify(),
    (t0x_sol - t0z_sol)
    .__mul__(V0x - vx)
    .__mul__(V0z - vz)
    .expand()
    .simplify()
    .__add__(px*vz - pz*vx) - (t2x_sol - t2z_sol)
    .__mul__(V2x - vx)
    .__mul__(V2z - vz)
    .expand()
    .simplify()
    .__add__(px*vz - pz*vx).simplify(),
    (t0y_sol - t0z_sol)
    .__mul__(V0y - vy)
    .__mul__(V0z - vz)
    .expand()
    .simplify()
    .__add__(py*vz - pz*vy) - (t2y_sol - t2z_sol)
    .__mul__(V2y - vy)
    .__mul__(V2z - vz)
    .expand()
    .simplify()
    .__add__(py*vz - pz*vy).simplify(),
]

for eq in equations:
    print(eq, "= 0")
for eq in equations:
    s = eq.coeff(px) * px
    for i in (py, pz, vx, vy, vz):
        s += eq.coeff(i) * i
    print((s - eq).simplify())


  t0 = (-P0x + px)/(V0x - vx) = (-P0y + py)/(V0y - vy) = (-P0z + pz)/(V0z - vz)
  t1 = (-P1x + px)/(V1x - vx) = (-P1y + py)/(V1y - vy) = (-P1z + pz)/(V1z - vz)
  t2 = (-P2x + px)/(V2x - vx) = (-P2y + py)/(V2y - vy) = (-P2z + pz)/(V2z - vz)
from t0x and t0y:
   -P0x*V0y + P0x*vy + P0y*V0x - P0y*vx - V0x*py + V0y*px - px*vy + py*vx = 0
from t0x and t0z:
   -P0x*V0z + P0x*vz + P0z*V0x - P0z*vx - V0x*pz + V0z*px - px*vz + pz*vx = 0
We can rewrite the equations above as:
   -P0x*V0y + P0x*vy + P0y*V0x - P0y*vx - V0x*py + V0y*px = px*vy - py*vx
   -P0x*V0z + P0x*vz + P0z*V0x - P0z*vx - V0x*pz + V0z*px = px*vz - pz*vx
we see that RHS is independent of the exact hailstone we are looking at
-P0x*V0y + P0x*vy + P0y*V0x - P0y*vx + P1x*V1y - P1x*vy - P1y*V1x + P1y*vx - V0x*py + V0y*px + V1x*py - V1y*px = 0
-P0x*V0z + P0x*vz + P0z*V0x - P0z*vx + P1x*V1z - P1x*vz - P1z*V1x + P1z*vx - V0x*pz + V0z*px + V1x*pz - V1z*px = 0
-P0y*V0z + P0y*vz + P0z*V0y - P0z*vy + P1y*V1z - P1y*vz - P1z*V1y + P1z*vy - V0

$$
\begin{cases}
-P_{0x}*V_{0y} + P_{0x}*v_y + P_{0y}*V_{0x} - P_{0y}*v_x + P_{1x}*V_{1y} - P_{1x}*v_y - P_{1y}*V_{1x} + P_{1y}*v_x - V_{0x}*p_y + V_{0y}*p_x + V_{1x}*p_y - V_{1y}*p_x = 0 \\
-P_{0x}*V_{0z} + P_{0x}*vz + P_{0z}*V_{0x} - P_{0z}*v_x + P_{1x}*V_{1z} - P_{1x}*vz - P_{1z}*V_{1x} + P_{1z}*v_x - V_{0x}*p_z + V_{0z}*p_x + V_{1x}*p_z - V_{1z}*p_x = 0 \\
-P_{0y}*V_{0z} + P_{0y}*vz + P_{0z}*V_{0y} - P_{0z}*v_y + P_{1y}*V_{1z} - P_{1y}*vz - P_{1z}*V_{1y} + P_{1z}*v_y - V_{0y}*p_z + V_{0z}*p_y + V_{1y}*p_z - V_{1z}*p_y = 0 \\
-P_{0x}*V_{0y} + P_{0x}*v_y + P_{0y}*V_{0x} - P_{0y}*v_x + P_{2x}*V_{2y} - P_{2x}*v_y - P_{2y}*V_{2x} + P_{2y}*v_x - V_{0x}*p_y + V_{0y}*p_x + V_{2x}*p_y - V_{2y}*p_x = 0 \\
-P_{0x}*V_{0z} + P_{0x}*vz + P_{0z}*V_{0x} - P_{0z}*v_x + P_{2x}*V_{2z} - P_{2x}*vz - P_{2z}*V_{2x} + P_{2z}*v_x - V_{0x}*p_z + V_{0z}*p_x + V_{2x}*p_z - V_{2z}*p_x = 0 \\
-P_{0y}*V_{0z} + P_{0y}*vz + P_{0z}*V_{0y} - P_{0z}*v_y + P_{2y}*V_{2z} - P_{2y}*vz - P_{2z}*V_{2y} + P_{2z}*v_y - V_{0y}*p_z + V_{0z}*p_y + V_{2y}*p_z - V_{2z}*p_y = 0 \\
\end{cases}
$$

In [57]:
def solve(data):
    P0, V0 = data[0]
    P1, V1 = data[1]
    P2, V2 = data[2]

    V0x, V0y, V0z = V0
    V1x, V1y, V1z = V1
    V2x, V2y, V2z = V2

    P0x, P0y, P0z = P0
    P1x, P1y, P1z = P1
    P2x, P2y, P2z = P2

    A = np.array([
        [V0y - V1y,-V0x + V1x,0,-P0y + P1y , P0x - P1x , 0],
        [V0z - V1z,0,-V0x + V1x,-P0z + P1z , 0 , P0x - P1x],
        [0,V0z - V1z,-V0y + V1y,0 , -P0z + P1z , P0y - P1y],
        [V0y - V2y,-V0x + V2x,0,-P0y + P2y , P0x - P2x , 0],
        [V0z - V2z,0,-V0x + V2x,-P0z + P2z , 0 , P0x - P2x],
        [0,V0z - V2z,-V0y + V2y,0 , -P0z + P2z , P0y - P2y],
    ])
    b = np.array([
        P0x*V0y - P0y*V0x - P1x*V1y + P1y*V1x,
        P0x*V0z - P0z*V0x - P1x*V1z + P1z*V1x,
        P0y*V0z - P0z*V0y - P1y*V1z + P1z*V1y,
        P0x*V0y - P0y*V0x - P2x*V2y + P2y*V2x,
        P0x*V0z - P0z*V0x - P2x*V2z + P2z*V2x,
        P0y*V0z - P0z*V0y - P2y*V2z + P2z*V2y,
    ])
    return np.linalg.solve(A, b)

In [60]:
px, py, pz, _, _, _ = solve(data)
px + py + pz

46.99999999999999

In [85]:
def parse_line(t: str):
    
    a, b = t.strip().split('@')
    p = np.array([int(x.strip()) for x in a.split(',')])
    v = np.array([int(x.strip()) for x in b.split(',')])

    return (p, v)

real_data = [parse_line(line) for i, line in enumerate(open('input.txt', 'r')) if i < 5]
real_data

[(array([211614908752320, 355884497165907, 259696313651729]),
  array([  15, -119,   26])),
 (array([403760160726375, 378047702508912, 174017730109516]),
  array([ -18, -130,  147])),
 (array([144186255945915, 328686782113692, 276690520845056]),
  array([  -7,  147, -255])),
 (array([299201969056161, 237456995776920,  10519998213462]),
  array([ 93,  50, 366])),
 (array([318259016385963, 232634818611690, 332436547677046]),
  array([  6,  92, -77]))]

In [87]:
px, py, pz, _, _, _ = solve(real_data)
px + py + pz

716599937560103.0